### ISSUE TITLE
deployctl doesn't respect configured JSX factory

### ISSUE THREAD

**Issue by mariusschulz** [denoland/deployctl#133]
I'm seeing different behavior when deploying a Deno app to Deno Deploy via automatic mode vs. the `deployctl` CLI (and consequently, the corresponding GitHub Action). The key problem is that `deployctl` seems to **ignore the specified JSX factory** whereas the deployment made via automatic mode seems to work fine.

## Repro

I've created a small repro repository (see https://github.com/mariusschulz/deno-deploy-jsx-config) and deployed the same commit to Deno Deploy, once via automatic mode and once via `deployctl`:

- ✅ **Working deployment** (deployed via automatic mode): https://deno-deploy-jsx-config-9bmta7c3g15g.deno.dev/
- ❌ **Broken deployment** (deployed via `deployctl`): https://deno-deploy-jsx-config-cny9m3wwnkcg.deno.dev/

## Expected Behavior

Both deployments should work.

## Actual Behavior

The deployment made via `deployctl` didn't respect the JSX factory specified in the [deno.json](https://github.com/mariusschulz/deno-deploy-jsx-config/blob/main/deno.json) file. I'm seeing this error in the logs, indicating that the JSX factory is configured to be `h`:

```
 ReferenceError: h is not defined
    at Server.serve.port (file:///src/main.tsx:4:20)
    at Server.#respond (https://deno.land/std@0.154.0/http/server.ts:219:43)
    at Server.#serveHttp (https://deno.land/std@0.154.0/http/server.ts:253:26)
```

**Comment by digitaldesigndj** [comment]
This is the source of the problems I had over at: https://github.com/denoland/fresh/issues/734

@lucacasonato explained it as this project needs to read and respect `deno.json`.
