### ISSUE TITLE
https://deno.com/deploy doesn't support Blob

### ISSUE THREAD

**Issue by oyzhen** [denoland/deployctl#28]
When I run locally, everything is OK, but failed on [https://deno.com/deploy](https://deno.com/deploy)

```
TypeError: Blob is not a constructor
    at html (https://raw.githubusercontent.com/oyzhen/oyzhen/517bc3a47b0245158fe573482fe2423876818960/libs/serve.ts:33:17)
    at https://raw.githubusercontent.com/oyzhen/oyzhen/517bc3a47b0245158fe573482fe2423876818960/main.ts:3:21
    at handleRequest (https://raw.githubusercontent.com/oyzhen/oyzhen/517bc3a47b0245158fe573482fe2423876818960/libs/serve.ts:85:20)
    at https://raw.githubusercontent.com/oyzhen/oyzhen/517bc3a47b0245158fe573482fe2423876818960/libs/serve.ts:97:27
    at innerInvokeEventListeners (deno:op_crates/web/02_event.js:750:27)
    at invokeEventListeners (deno:op_crates/web/02_event.js:785:5)
    at dispatch (deno:op_crates/web/02_event.js:660:11)
    at dispatchEvent (deno:op_crates/web/02_event.js:984:14)
    at receiveRequests (deno:js/99_main.js:94:18)
```

Repo: [oyzhen/oyzhen](https://github.com/oyzhen/oyzhen/tree/8139bcf20564f8886dad95d8143e0b4b17094c38)
URL: https://raw.githubusercontent.com/oyzhen/oyzhen/8139bcf20564f8886dad95d8143e0b4b17094c38/main.ts

**Comment by satyarohith** [comment]
Thanks for the report. We're looking into it.

**Comment by bnoordhuis** [comment]
Fix underway. Thanks for the report, @oyzhen.

**Comment by lucacasonato** [comment]
The issue is now resolved.

**Comment by oyzhen** [comment]
Good job!
