### ISSUE TITLE
quotes.ts example is failing to run

### ISSUE THREAD

**Issue by marcosvm** [denoland/deployctl#29]
I'm trying to run `quotes.ts` from https://deno.com/deploy/docs/tutorial-faunadb but it'll give me error messages below.

I'm not sure how to resolve the conflict error:

```
→ deployctl run ./quotes.ts
Check file:///Users/marcosvm/code/deno/quotes/$deno$eval.ts
error: TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file: DOMException, Event, EventTarget, EventListenerOrEventListenerObject, ProgressEvent, TextDecoder, TextEncoder, AbortController, URLSearchParams, URL, ReadableStreamReader, CountQueuingStrategy, ByteLengthQueuingStrategy, BlobPart, Blob, File, FormDataEntryValue, FormData, HeadersInit, Headers, RequestInfo, RequestCache, RequestCredentials, RequestMode, RequestRedirect, ReferrerPolicy, BodyInit, RequestDestination, Request, ResponseType, Response, CloseEvent, WebSocket, BinaryType, CompileError, Global, Instance, LinkError, Memory, Module, RuntimeError, Table, ImportExportKind, TableKind, ValueType, ExportValue, Exports, ImportValue, ModuleImports, Imports, BufferSource, MessageEvent, ErrorEvent, CustomEvent, Window
interface Account {
~~~~~~~~~
    at asset:///lib.dom.d.ts:25:1

    Conflicts are in this file.
    declare class DOMException extends Error {
    ~~~~~~~
        at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:11:1

TS2430 [ERROR]: Interface 'ReadableStreamDefaultReader<R>' incorrectly extends interface 'ReadableStreamGenericReader'.
  Types of property 'closed' are incompatible.
    Type 'Promise<void>' is not assignable to type 'Promise<undefined>'.
      Type 'void' is not assignable to type 'undefined'.
interface ReadableStreamDefaultReader<R = any> extends ReadableStreamGenericReader {
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.dom.d.ts:12597:11

TS2345 [ERROR]: Argument of type 'unknown' is not assignable to parameter of type 'VNode<{}>'.
  return new Response(render(jsx), {
                             ~~~
    at https://deno.land/x/sift@0.1.4/util.ts:22:30

TS2339 [ERROR]: Property 'keys' does not exist on type 'URLSearchParams'.
    for (const param of searchParams.keys()) {
                                     ~~~~
    at https://deno.land/x/sift@0.1.4/util.ts:72:38

TS2339 [ERROR]: Property 'keys' does not exist on type 'Headers'.
    for (const header of request.headers.keys()) {
                                         ~~~~
    at https://deno.land/x/sift@0.1.4/util.ts:95:42

TS2304 [ERROR]: Cannot find name 'body'.
    const { quote, author } = body;
                              ~~~~
    at file:///Users/marcosvm/code/deno/quotes/quotes.ts:36:31

TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file: DOMException, Event, EventTarget, EventListenerOrEventListenerObject, ProgressEvent, TextDecoder, TextEncoder, AbortController, URLSearchParams, URL, ReadableStreamReader, CountQueuingStrategy, ByteLengthQueuingStrategy, BlobPart, Blob, File, FormDataEntryValue, FormData, HeadersInit, Headers, RequestInfo, RequestCache, RequestCredentials, RequestMode, RequestRedirect, ReferrerPolicy, BodyInit, RequestDestination, Request, ResponseType, Response, CloseEvent, WebSocket, BinaryType, CompileError, Global, Instance, LinkError, Memory, Module, RuntimeError, Table, ImportExportKind, TableKind, ValueType, ExportValue, Exports, ImportValue, ModuleImports, Imports, BufferSource, MessageEvent, ErrorEvent, CustomEvent, Window
declare class DOMException extends Error {
~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:11:1

    Conflicts are in this file.
    interface Account {
    ~~~~~~~~~
        at asset:///lib.dom.d.ts:25:1

TS2403 [ERROR]: Subsequent variable declarations must have the same type.  Variable 'ReadableStreamDefaultReader' must be of type '{ new <R = any>(stream: ReadableStream<R>): ReadableStreamDefaultReader<R>; prototype: ReadableStreamDefaultReader<any>; }', but here has type '{ new <R>(stream: ReadableStream<R>): ReadableStreamDefaultReader<R>; prototype: ReadableStreamDefaultReader<any>; }'.
declare var ReadableStreamDefaultReader: {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:521:13

    'ReadableStreamDefaultReader' was also declared here.
    declare var ReadableStreamDefaultReader: {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at asset:///lib.dom.d.ts:12602:13

TS2314 [ERROR]: Generic type 'ReadableStreamReader' requires 1 type argument(s).
  prototype: ReadableStreamReader;
             ~~~~~~~~~~~~~~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:533:14

TS2314 [ERROR]: Generic type 'ReadableStreamReader' requires 1 type argument(s).
  new (): ReadableStreamReader;
          ~~~~~~~~~~~~~~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:534:11

TS2403 [ERROR]: Subsequent variable declarations must have the same type.  Variable 'ReadableStream' must be of type '{ new <R = any>(underlyingSource?: UnderlyingSource<R> | undefined, strategy?: QueuingStrategy<R> | undefined): ReadableStream<R>; prototype: ReadableStream<...>; }', but here has type '{ new (underlyingSource: UnderlyingByteSource, strategy?: { highWaterMark?: number | undefined; size?: undefined; } | undefined): ReadableStream<Uint8Array>; new <R = any>(underlyingSource?: UnderlyingSource<...> | undefined, strategy?: QueuingStrategy<...> | undefined): ReadableStream<...>; prototype: ReadableStrea...'.
declare var ReadableStream: {
            ~~~~~~~~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:658:13

    'ReadableStream' was also declared here.
    declare var ReadableStream: {
                ~~~~~~~~~~~~~~
        at asset:///lib.dom.d.ts:12580:13

TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'closed' must be of type 'Promise<undefined>', but here has type 'Promise<void>'.
  readonly closed: Promise<void>;
           ~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:719:12

    'closed' was also declared here.
        readonly closed: Promise<undefined>;
                 ~~~~~~
        at asset:///lib.dom.d.ts:18811:14

TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'ready' must be of type 'Promise<undefined>', but here has type 'Promise<void>'.
  readonly ready: Promise<void>;
           ~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:721:12

    'ready' was also declared here.
        readonly ready: Promise<undefined>;
                 ~~~~~
        at asset:///lib.dom.d.ts:18813:14

TS2403 [ERROR]: Subsequent variable declarations must have the same type.  Variable 'WritableStreamDefaultWriter' must be of type '{ new <W = any>(stream: WritableStream<W>): WritableStreamDefaultWriter<W>; prototype: WritableStreamDefaultWriter<any>; }', but here has type '{ new (): WritableStreamDefaultWriter<any>; prototype: WritableStreamDefaultWriter<any>; }'.
declare var WritableStreamDefaultWriter: {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:728:13

    'WritableStreamDefaultWriter' was also declared here.
    declare var WritableStreamDefaultWriter: {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at asset:///lib.dom.d.ts:18820:13

TS2375 [ERROR]: Duplicate number index signature.
  [index: number]: string;
  ~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:1653:3

TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'subtle' must be of type 'SubtleCrypto', but here has type 'null'.
  readonly subtle: null;
           ~~~~~~
    at file:///Users/marcosvm/Library/Caches/deno/https/deno.land/10dacc910db04e7ca67ef115b78ef6a413eff3504212fadcf8546401fbfc1e0d.ts:1749:12

    'subtle' was also declared here.
        readonly subtle: SubtleCrypto;
                 ~~~~~~
        at asset:///lib.dom.d.ts:3749:14

Found 16 errors.
error: Process exited with code 1
```

I'm using:
```
→ deno -V
deno 1.8.2
```
with deployctl installed from:

```
 deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -f https://deno.land/x/deploy/deployctl.ts
```

Thank you for your help.

**Comment by kt3k** [comment]
We have error in typings of the examples for now.

Please use the following command to skip the type checking:
```
deployctl run --no-check ./quotes.ts
```

**Comment by satyarohith** [comment]
@marcosvm Thanks for opening the issue. The tutorial is updated.

**Comment by marcosvm** [comment]
It's working now, thank you for the quick response.
