### ISSUE TITLE
Watcher throws bland message when importing nonexistent module

### ISSUE THREAD

**Issue by danopia** [denoland/deployctl#34]
When `mod.ts` imports `nonexistent.ts`:

```
> deployctl run mod.ts --watch
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    const watcher = Deno.watchFs(deps);
^
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at Object.jsonOpSync (deno:core/core.js:372:12)
    at new FsWatcher (deno:runtime/js/40_fs_events.js:13:24)
    at Object.watchFs (deno:runtime/js/40_fs_events.js:49:12)
    at watch (https://deno.land/x/deploy@0.1.0/src/subcommands/run.ts:108:1)
    at async default (https://deno.land/x/deploy@0.1.0/src/subcommands/run.ts:89:1)
    at async https://deno.land/x/deploy@0.1.0/deployctl.ts:61:1
```

Comparatively, `deno cache` shows the actual issue:

```
> deno cache mod.ts 
error: Cannot resolve module "file:///work/nonexistent.ts" from "file:///work/mod.ts".
    at file:///work/mod.ts:1:0
```

This is a trivial example, which can be less obvious when refactoring files in a larger project with the watcher running.

**Comment by lucacasonato** [comment]
Very interesting... I would have expected our internal call to `deno info` would expose `error: Cannot resolve module "file:///work/nonexistent.ts" from "file:///work/mod.ts". `, but it seems not. This will need some more digging then :-)

**Comment by danopia** [comment]
I also noticed that this Uncaught error then causes the deployctl instance to exit (makes sense given that Deno programs can't catch uncaught exceptions). So a running --watch instance will shut down the first time a bad import is found
