### ISSUE TITLE
Serving local files broken with 1.9.1

### ISSUE THREAD

**Issue by satyarohith** [denoland/deployctl#43]
Getting the below error.
```
error: Uncaught (in promise) TypeError: HEAD and GET requests may not have a body.
        this.#request = new Request(new URL(stdReq.url, `http://${host}`).toString(), {
                        ^
    at new Request (deno:op_crates/fetch/23_request.js:273:15)
    at new FetchEvent (https://deno.land/x/deploy@0.2.0/src/runtime.bundle.js:2551:25)
    at serve1 (https://deno.land/x/deploy@0.2.0/src/runtime.bundle.js:2612:30)
error: Process exited with code 1
```

Reproduction:

1. Create a file named local.js and paste the below code
```js
addEventListener("fetch", (event) => {
  event.respondWith(fetch(new URL("local.js", import.meta.url)));
});
```
2. Run `deployctl run local.js`

**Comment by lucacasonato** [comment]
Will be resolved by #42.
