### ISSUE TITLE
BadResource error when file changes in watch mode

### ISSUE THREAD

**Issue by tmdh** [denoland/deployctl#75]
Using example in https://deno.com/examples/hello.js or any script.
This error is produced by changing the file.
```
Check file:///mnt/d/code/tmdh-api/$deno$eval.ts
Check data:application/typescript;base64,aW1wb3J0IHR5cGUge30gZnJvbSAiZmlsZTovLy9ob21lL3RhcmVxdWUvLmNhY2hlL2Rlbm8vaHR0cHMvZGVuby5sYW5kLzM4OTc2MjU3OGRmMmE4YWUwYTZkMTg5NWQ1MWFmMTVjY2QxNzFiODEyMTNjYmVmNDQ4NGM0MTQ1MjJmYzE0MmYudHMiO2ltcG9ydCB0eXBlIHt9IGZyb20gImZpbGU6Ly8vaG9tZS90YXJlcXVlLy5jYWNoZS9kZW5vL2h0dHBzL2Rlbm8ubGFuZC9hNTQ4NzNjZTc0NTQ5MTk0MmFiZGU4ODc0YjVlYTkyZjM0M2E5YmU0YTU0MTNlNzhkZmU3Yzk0ZmNmZTJiMjAxLnRzIjtpbXBvcnQgdHlwZSB7fSBmcm9tICJmaWxlOi8vL2hvbWUvdGFyZXF1ZS8uY2FjaGUvZGVuby9odHRwcy9kZW5vLmxhbmQvNzQ2N2JjNzY2Mzg4MGI1MzM5ZjM2ZWUwYWQ2ZGNiY2QzNDljMmI5YzM5NmE0OGI0MDYxNjc5YzNiZWNkMTNiMi50cyI7aW1wb3J0ICJmaWxlOi8vL21udC9kL2NvZGUvdG1kaC1hcGkvaGVsbG8uanMiOw==
Listening on http://0.0.0.0:8080
/mnt/d/code/tmdh-api/hello.js changed. Restarting...
Check file:///mnt/d/code/tmdh-api/$deno$eval.ts
/mnt/d/code/tmdh-api/hello.js changed. Restarting...
error: Uncaught (in promise) BadResource: Bad resource ID
}
 ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at opSync (deno:core/01_core.js:140:12)
    at Object.close (deno:core/01_core.js:148:5)
    at FsWatcher.return (deno:runtime/js/40_fs_events.js:43:12)
    at https://deno.land/x/deploy@0.3.0/src/subcommands/run.ts:146:2
```

OS: Linux
Deno version: 
```
deno 1.13.0 (release, x86_64-unknown-linux-gnu)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by lucacasonato** [comment]
Thanks for contributing by opening an issue.

This project is being archived because you can now use `deno run` to run your Deploy scripts locally: https://deno.com/deploy/docs/running-scripts-locally/. As such, I will close this issue.

If you have feedback about Deno Deploy, please open an issue on this repo: https://github.com/denoland/deploy_feedback
